name: Compile LaTeX

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex

      - uses: actions/upload-artifact@v4
        with:
          name: template-poly
          path: template.pdf

      - name: Upload PDF to latest release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          prerelease: true
          files: template.pdf
